#!/bin/bash

# This file is part of LFScript. LFScript is released under the MIT license.
# Copyright (C) 2007-2014 Marcel van den Boer

REQUIRES="postlfs"
POSTINST="true"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

export XORG_PREFIX="/usr"

export XORG_CONFIG="--prefix=$XORG_PREFIX --sysconfdir=/etc \
    --localstatedir=/var --disable-static"

cat > ${FAKEROOT}/etc/profile.d/xorg.sh << "EOF"
XORG_PREFIX="/usr"
XORG_CONFIG="--prefix=$XORG_PREFIX --sysconfdir=/etc --localstatedir=/var --disable-static"
export XORG_PREFIX XORG_CONFIG
EOF
chmod 644 ${FAKEROOT}/etc/profile.d/xorg.sh

if [ "${XORG_PREFIX}" == "/usr" ]; then
    return
fi

cat >> ${FAKEROOT}/etc/profile.d/xorg.sh << "EOF"

pathappend $XORG_PREFIX/bin             PATH
pathappend $XORG_PREFIX/lib/pkgconfig   PKG_CONFIG_PATH
pathappend $XORG_PREFIX/share/pkgconfig PKG_CONFIG_PATH

pathappend $XORG_PREFIX/lib             LIBRARY_PATH
pathappend $XORG_PREFIX/include         C_INCLUDE_PATH
pathappend $XORG_PREFIX/include         CPLUS_INCLUDE_PATH

ACLOCAL='aclocal -I $XORG_PREFIX/share/aclocal'

export PATH PKG_CONFIG_PATH ACLOCAL LIBRARY_PATH C_INCLUDE_PATH CPLUS_INCLUDE_PATH
EOF

echo "$XORG_PREFIX/lib" >> ${FAKEROOT}/etc/ld.so.conf.d/xorg-config-prefix.conf

ln -s $XORG_PREFIX/share/X11 ${FAKEROOT}/usr/share/X11

install -v -m755 -d ${FAKEROOT}$XORG_PREFIX &&
install -v -m755 -d ${FAKEROOT}$XORG_PREFIX/lib &&
ln -s lib ${FAKEROOT}$XORG_PREFIX/lib64

###################################################
}; postinst() { # POST-INSTALLATION CONFIGURATION #
###################################################

sed "s@/usr/X11R6@$XORG_PREFIX@g" -i /etc/man_db.conf

#################
} # END OF FILE #
#################

