#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-07-25 / r13664) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://alsa.cybermirror.org/utils/alsa-utils-1.0.28.tar.bz2
          http://www.linuxfromscratch.org/blfs/downloads/svn/blfs-bootscripts-20140530.tar.bz2"
MD5SUMLIST="361552d5b1cacd0a1e7ba09e69990211
            8c76fe0fc24cbeb640f4e14be2747eb2"
REQUIRES="alsa-lib"
POSTINST="now"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --disable-alsaconf --disable-xmlto
make

make DESTDIR=${FAKEROOT} install

includeBootscript alsa

###################################################
}; postinst() { # POST-INSTALLATION CONFIGURATION #
###################################################

touch /var/lib/alsa/asound.state
alsactl store

#usermod -a -G audio <username>

#################
} # END OF FILE #
#################

