#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-07-25 / r13664) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://dbus.freedesktop.org/releases/dbus/dbus-1.8.6.tar.gz
          http://www.linuxfromscratch.org/blfs/downloads/svn/blfs-bootscripts-20140530.tar.bz2"
MD5SUMLIST="6a08ba555d340e9dfe2d623b83c0eea8
            8c76fe0fc24cbeb640f4e14be2747eb2"
POSTINST="now"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

#groupadd -g 18 messagebus
#useradd -c "D-Bus Message Daemon User" -d /var/run/dbus \
#        -u 18 -g messagebus -s /bin/false messagebus

./configure --prefix=/usr                  \
            --sysconfdir=/etc              \
            --localstatedir=/var           \
            --with-console-auth-dir=/run/console/ \
            --without-systemdsystemunitdir \
            --disable-systemd              \
            --disable-static
make

make DESTDIR=${FAKEROOT} install
mv -v ${FAKEROOT}/usr/share/doc/dbus ${FAKEROOT}/usr/share/doc/dbus-1.8.6

#make distclean
#./configure --enable-tests --enable-asserts
#make
#make check
#make distclean

#sed -i -e 's:run-test.sh:$(NULL):g' test/name-test/Makefile.in

cat > ${FAKEROOT}/etc/dbus-1/session-local.conf << "EOF"
<!DOCTYPE busconfig PUBLIC
 "-//freedesktop//DTD D-BUS Bus Configuration 1.0//EN"
 "http://www.freedesktop.org/standards/dbus/1.0/busconfig.dtd">
<busconfig>

  <!-- Search for .service files in /usr/local -->
  <servicedir>/usr/local/share/dbus-1/services</servicedir>

</busconfig>
EOF

includeBootscript dbus

###################################################
}; postinst() { # POST-INSTALLATION CONFIGURATION #
###################################################

dbus-uuidgen --ensure

## Start the D-Bus session daemon
#eval `dbus-launch`
#export DBUS_SESSION_BUS_ADDRESS

## Kill the D-Bus session daemon
#kill $DBUS_SESSION_BUS_PID

#################
} # END OF FILE #
#################

