#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-07-25 / r13664) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://roy.marples.name/downloads/dhcpcd/dhcpcd-6.4.2.tar.bz2
          http://www.linuxfromscratch.org/blfs/downloads/svn/blfs-bootscripts-20140530.tar.bz2"
MD5SUMLIST="3ba26bd6e0cd2f973bfbcd3c08ebc93b
            8c76fe0fc24cbeb640f4e14be2747eb2"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --libexecdir=/lib/dhcpcd \
            --dbdir=/var/tmp
make

make DESTDIR=${FAKEROOT} install

includeBootscript service-dhcpcd

#cat > /etc/sysconfig/ifconfig.eth0 << "EOF"
#ONBOOT="yes"
#IFACE="eth0"
#SERVICE="dhcpcd"
#DHCP_START="-b -q <insert appropriate start options here>"
#DHCP_STOP="-k <insert additional stop options here>"
#EOF

#cat > /etc/sysconfig/ifconfig.eth0 << "EOF"
#ONBOOT="yes"
#IFACE="eth0"
#SERVICE="dhcpcd"
#DHCP_START="-b -q -S ip_address=192.168.0.10/24 -S routers=192.168.0.1"
#DHCP_STOP="-k"
#EOF

cat > ${FAKEROOT}/etc/resolv.conf.head << "EOF"
# OpenDNS servers
nameserver 208.67.222.222
nameserver 208.67.220.220
EOF

#################
} # END OF FILE #
#################

