#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-07-25 / r13664) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://www.freedesktop.org/software/harfbuzz/release/harfbuzz-0.9.32.tar.bz2"
MD5SUMLIST="b8c19f87ee7da0813c77a7b43bef4c98"
REQUIRES="freetype2 glib2"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr --with-gobject
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

