#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-07-25 / r13664) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://www.netfilter.org/projects/iptables/files/iptables-1.4.21.tar.bz2
          http://www.linuxfromscratch.org/blfs/downloads/svn/blfs-bootscripts-20140530.tar.bz2"
MD5SUMLIST="536d048c8e8eeebcd9757d0863ebb0c0
            8c76fe0fc24cbeb640f4e14be2747eb2"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr                \
            --sbindir=/sbin              \
            --with-xtlibdir=/lib/xtables \
            --enable-libipq
make

make DESTDIR=${FAKEROOT} install
ln -sfv ../../sbin/xtables-multi ${FAKEROOT}/usr/bin/iptables-xml
for file in ip4tc ip6tc ipq iptc xtables
do
  mv -v ${FAKEROOT}/usr/lib/lib${file}.so.* ${FAKEROOT}/lib
  ln -sfv ../../lib/$(readlink ${FAKEROOT}/usr/lib/lib${file}.so) ${FAKEROOT}/usr/lib/lib${file}.so
done

includeBootscript iptables

#################
} # END OF FILE #
#################

