#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-07-25 / r13664) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://dri.freedesktop.org/libdrm/libdrm-2.4.54.tar.bz2"
MD5SUMLIST="56e98a9c2073c3fab7f95e003b657f46"
REQUIRES="x7lib"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

sed -e "/pthread-stubs/d" -i configure.ac
autoreconf -fiv
./configure --prefix=/usr --enable-udev
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

