#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-07-25 / r13664) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://libndp.org/files/libndp-1.3.tar.gz"
MD5SUMLIST="e4ac1fce2faa664ba8b20df581bf30ea"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr         \
             --sysconfdir=/etc    \
             --localstatedir=/var \
             --disable-static
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

