#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-07-25 / r13664) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://people.freedesktop.org/~aplattner/vdpau/libvdpau-0.8.tar.gz"
MD5SUMLIST="acf68adc8b8ff4f72be6e8679abc284e"
REQUIRES="cmake x7lib xorg-env"
POSTINST="now"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure $XORG_CONFIG
make

make DESTDIR=${FAKEROOT} install

###################################################
}; postinst() { # POST-INSTALLATION CONFIGURATION #
###################################################

echo "export VDPAU_DRIVER=va_gl" >> /etc/profile.d/xorg.sh

#################
} # END OF FILE #
#################

