#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-07-25 / r13664) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://ftp.gnome.org/pub/gnome/sources/NetworkManager/0.9/NetworkManager-0.9.10.0.tar.xz
          http://www.linuxfromscratch.org/blfs/downloads/svn/blfs-bootscripts-20140530.tar.bz2"
MD5SUMLIST="21b9051dbbd6434df4624a90ca9d71b6
            8c76fe0fc24cbeb640f4e14be2747eb2"
REQUIRES="dbus-glib dhcpcd iptables libndp libnl newt nss udev-extras"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr        \
            --sysconfdir=/etc    \
            --localstatedir=/var \
            --with-nmtui         \
            --disable-ppp        \
            --with-systemdsystemunitdir=no
make

make DESTDIR=${FAKEROOT} install

cat >> ${FAKEROOT}/etc/NetworkManager/NetworkManager.conf << "EOF"
[main]
plugins=keyfile
EOF

includeBootscript networkmanager

#################
} # END OF FILE #
#################

