#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-07-25 / r13664) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://xorg.freedesktop.org/archive/individual/driver/glamor-egl-0.6.0.tar.bz2"
MD5SUMLIST="b3668594675f71a75153ee52dbd35535"
REQUIRES="xorg-env xorg-server"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure $XORG_CONFIG --enable-glx-tls
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

