#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-07-25 / r13664) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://xcb.freedesktop.org/dist/xcb-proto-1.10.tar.bz2"
MD5SUMLIST="ade74b8e9c870dc7515adfa209e66063"
REQUIRES="python2 xorg-env"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure $XORG_CONFIG

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

