#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-07-25 / r13664) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://xorg.freedesktop.org/releases/individual/app/xinit-1.3.3.tar.bz2"
MD5SUMLIST="3b8da0e6237aee9828cc809c647510a7"
REQUIRES="twm xclock xorg-env xterm"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure $XORG_CONFIG \
            --with-xinitdir=/etc/X11/app-defaults
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

