#!/bin/bash

# The instructions in this file are extracted from
# 'Linux From Scratch 7.6' (SVN-20140723 / r10652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Linux From Scratch is released under the MIT license.
# Copyright (C) 1999-2014, Gerard Beekmans

WGETLIST="http://sourceforge.net/projects/check/files/check/0.9.13/check-0.9.13.tar.gz"
MD5SUMLIST="95530868f81a9496b2518fd2b713008a"

###################################################
preparation() { # CONSTRUCTING A TEMPORARY SYSTEM #
###################################################

PKG_CONFIG= ./configure --prefix=/tools

make

make install

#################
} # END OF FILE #
#################

