#!/bin/bash

# The instructions in this file are extracted from
# 'Linux From Scratch 7.6' (SVN-20140723 / r10652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Linux From Scratch is released under the MIT license.
# Copyright (C) 1999-2014, Gerard Beekmans

WGETLIST="http://downloads.sourceforge.net/project/porg/porg-0.7.tar.xz?r=http%3A%2F%2Fsourceforge.net%2Fprojects%2Fporg%2Ffiles%2F&ts=1406827481&use_mirror=citylan"
MD5SUMLIST="dontverify"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr --disable-grop

make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

