#!/bin/bash

# The instructions in this file are extracted from
# 'Linux From Scratch 7.6' (SVN-20140723 / r10652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Linux From Scratch is released under the MIT license.
# Copyright (C) 1999-2014, Gerard Beekmans

WGETLIST="http://ftp.gnu.org/gnu/tar/tar-1.27.1.tar.xz
          http://www.linuxfromscratch.org/patches/lfs/development/tar-1.27.1-manpage-1.patch"
MD5SUMLIST="e0382a4064e09a4943f3adeff1435978
            321f85ec32733b1a9399e788714a5156"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

patch -Np1 -i ../tar-1.27.1-manpage-1.patch

FORCE_UNSAFE_CONFIGURE=1  \
./configure --prefix=/usr \
            --bindir=/bin

make

porg -lp tar "make DESTDIR=${FAKEROOT} install"
make DESTDIR=${FAKEROOT} -C doc install-html docdir=/usr/share/doc/tar-1.27.1

perl tarman > ${FAKEROOT}/usr/share/man/man1/tar.1

######################################################
}; preparation() { # CONSTRUCTING A TEMPORARY SYSTEM #
######################################################

./configure --prefix=/tools

make

make install

#################
} # END OF FILE #
#################

