#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-07-25 / r13664) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://download.kde.org/stable/akonadi/src/akonadi-1.12.1.tar.bz2"
MD5SUMLIST="9a4a99d10e003a267a515fc60de4f817"
REQUIRES="boost mariadb postgresql shared-mime-info sqlite"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

mkdir build
cd    build

cmake -DCMAKE_INSTALL_PREFIX=$KDE_PREFIX  \
      -DCMAKE_PREFIX_PATH=$QT4DIR          \
      -DCMAKE_BUILD_TYPE=Release           \
      -DINSTALL_QSQLITE_IN_QT_PREFIX=TRUE  \
      -Wno-dev ..
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

