#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-07-25 / r13664) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://sourceforge.net/projects/bridge/files/bridge/bridge-utils-1.5.tar.gz
          http://www.linuxfromscratch.org/blfs/downloads/svn/blfs-bootscripts-20140530.tar.bz2
          http://www.linuxfromscratch.org/patches/blfs/svn/bridge-utils-1.5-linux_3.8_fix-1.patch"
MD5SUMLIST="ec7b381160b340648dede58c31bb2238
            8c76fe0fc24cbeb640f4e14be2747eb2
            dontverify"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

patch -Np1 -i ../bridge-utils-1.5-linux_3.8_fix-1.patch
autoconf -o configure configure.in
./configure --prefix=/usr
make

make DESTDIR=${FAKEROOT} install

includeBootscript service-bridge

#cat > /etc/sysconfig/ifconfig.br0 << "EOF"
#ONBOOT=yes
#IFACE=br0
#SERVICE="bridge ipv4-static"  # Space separated
#IP=192.168.1.32
#GATEWAY=192.168.1.1
#PREFIX=24
#BROADCAST=192.168.1.255
#CHECK_LINK=no                 # Don't check before bridge is created
#STP=no                        # Spanning tree protocol, default no
#INTERFACE_COMPONENTS="eth0"   # Add to IFACE, space separated devices
#IP_FORWARD=true
#EOF

#################
} # END OF FILE #
#################

