#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-07-25 / r13664) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://ftp.stack.nl/pub/doxygen/doxygen-1.8.7.src.tar.gz"
MD5SUMLIST="ff0529df773301f63db82c25137b7fd8"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix /usr \
            --docdir /usr/share/doc/doxygen-1.8.7
make

make DESTDIR=${FAKEROOT} MAN1DIR=share/man/man1 install

make DESTDIR=${FAKEROOT} install_docs

#################
} # END OF FILE #
#################

