#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-07-25 / r13664) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://ftp.gnu.org/gnu/gdb/gdb-7.7.1.tar.bz2"
MD5SUMLIST="77b20b515e7c25f032cb9732a66620fe"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr --with-system-readline
make

make DESTDIR=${FAKEROOT} -C gdb install

#################
} # END OF FILE #
#################

