#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-07-25 / r13664) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

REQUIRES="apache-ant bazaar check cmake cvs dejagnu doxygen elfutils expect gc gcc-ada gcc-java gdb general-prog-python-modules git guile java junit librep llvm lua mercurial nasm npapi-sdk openjdk python2 python3 ruby scons slang subversion swig tcl tk vala valgrind yasm"
TAGS="group"

