#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-07-25 / r13664) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="ftp://ftp.gnupg.org/gcrypt/gnupg/gnupg-2.0.25.tar.bz2"
MD5SUMLIST="048d8de797125f1d8e6cf3bdff9e2d12"
REQUIRES="libassuan libgcrypt libksba pth"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr \
            --enable-symcryptrun \
            --docdir=/usr/share/doc/gnupg-2.0.25
make

makeinfo --html --no-split -o doc/gnupg_nochunks.html doc/gnupg.texi
makeinfo --plaintext       -o doc/gnupg.txt           doc/gnupg.texi

make -C doc pdf ps html

make DESTDIR=${FAKEROOT} install
ln -sv gpg2  ${FAKEROOT}/usr/bin/gpg
ln -sv gpgv2 ${FAKEROOT}/usr/bin/gpgv

install -v -m755 -d ${FAKEROOT}/usr/share/doc/gnupg-2.0.25/html
install -v -m644    doc/gnupg_nochunks.html \
                    ${FAKEROOT}/usr/share/doc/gnupg-2.0.25/gnupg.html
install -v -m644    doc/*.texi doc/gnupg.txt \
                    ${FAKEROOT}/usr/share/doc/gnupg-2.0.25

install -v -m644 doc/gnupg.html/* \
                 ${FAKEROOT}/usr/share/doc/gnupg-2.0.25/html
install -v -m644 doc/gnupg.{pdf,dvi,ps} \
                 ${FAKEROOT}/usr/share/doc/gnupg-2.0.25

#################
} # END OF FILE #
#################

