#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-07-25 / r13664) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="ftp://ftp.gnupg.org/gcrypt/gpgme/gpgme-1.5.0.tar.bz2"
MD5SUMLIST="29e90462b29d445665e8728c66464a4f"
REQUIRES="libassuan"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr        \
            --disable-fd-passing \
            --disable-gpgsm-test
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

