#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-07-25 / r13664) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="ftp://ftp.gnupg.org/gcrypt/libassuan/libassuan-2.1.1.tar.bz2"
MD5SUMLIST="757243cc4a71b30ed8d8dbe784035d36"
REQUIRES="libgpg-error"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr
make

make -C doc pdf ps

make DESTDIR=${FAKEROOT} install

install -v -dm755 ${FAKEROOT}/usr/share/doc/libassuan-2.1.1
install -v -m644  doc/assuan.{pdf,ps,dvi} \
                  ${FAKEROOT}/usr/share/doc/libassuan-2.1.1

#################
} # END OF FILE #
#################

