#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-07-25 / r13664) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://www.videolan.org/pub/libdvdcss/1.2.13/libdvdcss-1.2.13.tar.bz2"
MD5SUMLIST="53cfc52a60a156763c425572e5179273"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr    \
            --disable-static \
            --docdir=/usr/share/doc/libdvdcss-1.2.13
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

