#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-07-25 / r13664) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://ftp.gnu.org/gnu/libidn/libidn-1.28.tar.gz"
MD5SUMLIST="43a6f14b16559e10a492acc65c4b0acc"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr --disable-static
make

make DESTDIR=${FAKEROOT} install

find doc -name "Makefile*" -delete
rm -rf -v doc/{gdoc,idn.1,stamp-vti,man,texi}
mkdir -v       ${FAKEROOT}/usr/share/doc/libidn-1.28
cp -r -v doc/* ${FAKEROOT}/usr/share/doc/libidn-1.28

#################
} # END OF FILE #
#################

