#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-07-25 / r13664) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="https://webp.googlecode.com/files/libwebp-0.4.0.tar.gz"
MD5SUMLIST="c8dd1d26eb9566833aba269b86d97e68"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

sed -i '/DGifCloseFile/s:gif:&, NULL:g' examples/gif2webp.c
./configure --prefix=/usr --disable-static
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

