#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-07-25 / r13664) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://downloads.sourceforge.net/lxde/lxde-icon-theme-0.5.0.tar.bz2"
MD5SUMLIST="346e1aecf805892b106b4d4b0f26e5cc"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr

make DESTDIR=${FAKEROOT} install

gtk-update-icon-cache -qf ${FAKEROOT}/usr/share/icons/nuoveXT2

#################
} # END OF FILE #
#################

