#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-07-25 / r13664) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://ftp.gnu.org/gnu/parted/parted-3.1.tar.xz"
MD5SUMLIST="5d89d64d94bcfefa9ce8f59f4b81bdcb"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

sed -i parted/ui.c \
    -e "s:(CPPFunction\*) complete:(rl_completion_func_t\*) complete:"
./configure --prefix=/usr --disable-static
make

make -C doc html
makeinfo --html      -o doc/html       doc/parted.texi
makeinfo --plaintext -o doc/parted.txt doc/parted.texi

texi2pdf             -o doc/parted.pdf doc/parted.texi
texi2dvi             -o doc/parted.dvi doc/parted.texi
dvips                -o doc/parted.ps  doc/parted.dvi

make DESTDIR=${FAKEROOT} install
install -v -m755 -d ${FAKEROOT}/usr/share/doc/parted-3.1/html
install -v -m644    doc/html/* \
                    ${FAKEROOT}/usr/share/doc/parted-3.1/html
install -v -m644    doc/{FAT,API,parted.{txt,html}} \
                    ${FAKEROOT}/usr/share/doc/parted-3.1

install -v -m644 doc/FAT doc/API doc/parted.{pdf,ps,dvi} \
                    ${FAKEROOT}/usr/share/doc/parted-3.1

#################
} # END OF FILE #
#################

