#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-07-25 / r13664) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://ftp.postgresql.org/pub/source/v9.3.4/postgresql-9.3.4.tar.bz2
          http://www.linuxfromscratch.org/blfs/downloads/svn/blfs-bootscripts-20140530.tar.bz2"
MD5SUMLIST="d0a41f54c377b2d2fab4a003b0dac762
            8c76fe0fc24cbeb640f4e14be2747eb2"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

sed -i '/DEFAULT_PGSOCKET_DIR/s@/tmp@/run/postgresql@' src/include/pg_config_manual.h
sed -i -e 's@psql\\"@& -h /tmp@' src/test/regress/pg_regress{,_main}.c
sed -i -e 's@gres\\"@& -k /tmp@' src/test/regress/pg_regress.c
./configure --prefix=/usr          \
            --enable-thread-safety \
            --docdir=/usr/share/doc/postgresql-9.3.4
make

make DESTDIR=${FAKEROOT} install
make DESTDIR=${FAKEROOT} install-docs

make -C contrib/<SUBDIR-NAME> install

install -v -dm700 ${FAKEROOT}/srv/pgsql/data
install -v -dm755 ${FAKEROOT}/run/postgresql
groupadd -g 41 postgres
useradd -c "PostgreSQL Server" -g postgres -d ${FAKEROOT}/srv/pgsql/data \
        -u 41 postgres
chown -Rv postgres:postgres ${FAKEROOT}/srv/pgsql ${FAKEROOT}/run/postgresql
su - postgres -c '/usr/bin/initdb -D ${FAKEROOT}/srv/pgsql/data'

su - postgres -c '/usr/bin/postmaster -D ${FAKEROOT}/srv/pgsql/data > \
    ${FAKEROOT}/srv/pgsql/data/logfile 2>&1 &'

su - postgres -c '/usr/bin/createdb test'
echo "create table t1 ( name varchar(20), state_province varchar(20) );" \
    | (su - postgres -c '/usr/bin/psql test ')
echo "insert into t1 values ('Billy', 'NewYork');" \
    | (su - postgres -c '/usr/bin/psql test ')
echo "insert into t1 values ('Evanidus', 'Quebec');" \
    | (su - postgres -c '/usr/bin/psql test ')
echo "insert into t1 values ('Jesse', 'Ontario');" \
    | (su - postgres -c '/usr/bin/psql test ')
echo "select * from t1;" | (su - postgres -c '/usr/bin/psql test')

includeBootscript postgresql

#################
} # END OF FILE #
#################

