#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-07-25 / r13664) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://ftp.samba.org/pub/samba/stable/samba-4.1.9.tar.gz
          http://www.linuxfromscratch.org/blfs/downloads/svn/blfs-bootscripts-20140530.tar.bz2"
MD5SUMLIST="f9efc506e08c680d2b79b13be28c959c
            8c76fe0fc24cbeb640f4e14be2747eb2"
REQUIRES="python2"
POSTINST="now"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure                             \
    --prefix=/usr                       \
    --sysconfdir=/etc                   \
    --localstatedir=/var                \
    --with-piddir=/run/samba            \
    --with-pammodulesdir=/lib/security  \
    --without-systemd                   \
    --enable-fhs                        \
    --enable-nss-wrapper

make

sed -i "/samba3.blackbox.failure.failure/i \^samba3.raw.eas" selftest/knownfail

make DESTDIR=${FAKEROOT} install

mv -v ${FAKEROOT}/usr/lib/libnss_win{s,bind}.so*   ${FAKEROOT}/lib
ln -v -sf ../../lib/libnss_winbind.so.2 ${FAKEROOT}/usr/lib/libnss_winbind.so
ln -v -sf ../../lib/libnss_wins.so.2    ${FAKEROOT}/usr/lib/libnss_wins.so

install -v -m644    examples/smb.conf.default ${FAKEROOT}/etc/samba

mkdir -pv ${FAKEROOT}/etc/openldap/schema

install -v -m644    examples/LDAP/README              \
                    ${FAKEROOT}/etc/openldap/schema/README.LDAP
                    
install -v -m644    examples/LDAP/samba*              \
                    ${FAKEROOT}/etc/openldap/schema
                    
install -v -m755    examples/LDAP/{get*,ol*} \
                    ${FAKEROOT}/etc/openldap/schema

install -v -m755 -d ${FAKEROOT}/usr/share/doc/samba-4.1.9

install -v -m644    lib/ntdb/doc/design.pdf \
                    ${FAKEROOT}/usr/share/doc/samba-4.1.9

includeBootscript samba

includeBootscript winbindd

###################################################
}; postinst() { # POST-INSTALLATION CONFIGURATION #
###################################################

ln -v -sf /usr/bin/smbspool /usr/lib/cups/backend/smb

groupadd -g 99 nogroup
useradd -c "Unprivileged Nobody" -d /dev/null -g nogroup \
    -s /bin/false -u 99 nobody

#################
} # END OF FILE #
#################

