#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-07-25 / r13664) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://serf.googlecode.com/svn/src_releases/serf-1.3.6.tar.bz2"
MD5SUMLIST="7fe38fa6eab078e0beabf291d8e4995d"
REQUIRES="apr-util openssl scons"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

sed -i "/Append/s:RPATH=libdir,::"   SConstruct
sed -i "/Default/s:lib_static,::"    SConstruct
sed -i "/Alias/s:install_static,::"  SConstruct
scons PREFIX=/usr

scons PREFIX=/usr install

#################
} # END OF FILE #
#################

