#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-07-25 / r13664) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://download.videolan.org/pub/videolan/vlc/2.1.5/vlc-2.1.5.tar.xz"
MD5SUMLIST="3941b561f590cc95ca5e795213cba2f2"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

sed -i 's:libsmbclient.h:samba-4.0/&:' modules/access/smb.c
./bootstrap
./configure --prefix=/usr
make

make DESTDIR=${FAKEROOT} docdir=/usr/share/doc/vlc-2.1.5 install

#################
} # END OF FILE #
#################

