#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-07-25 / r13664) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://ftp.debian.org/debian/pool/main/w/whois/whois_5.1.4.tar.xz"
MD5SUMLIST="02ad3adf1cb4f209f06f9c8266c79887"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

make

make DESTDIR=${FAKEROOT} prefix=/usr install-whois
make DESTDIR=${FAKEROOT} prefix=/usr install-mkpasswd
make DESTDIR=${FAKEROOT} prefix=/usr install-pos

#################
} # END OF FILE #
#################

