#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-07-25 / r13664) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="http://launchpad.net/wicd/1.7/1.7.2.4/+download/wicd-1.7.2.4.tar.gz
          http://www.linuxfromscratch.org/blfs/downloads/svn/blfs-bootscripts-20140530.tar.bz2"
MD5SUMLIST="c2435ddfdef0b9898852d72a85a45f0f
            8c76fe0fc24cbeb640f4e14be2747eb2"
REQUIRES="dbus-python net-tools python2 wireless-tools"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

sed -i '/wpath.logrotate\|wpath.systemd/d' setup.py
rm po/*.po
python setup.py configure --no-install-kde     \
                          --no-install-acpi    \
                          --no-install-pmutils \
                          --no-install-init

python setup.py install --root=${FAKEROOT}

includeBootscript wicd

#################
} # END OF FILE #
#################

