#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-07-25 / r13664) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

WGETLIST="ftp://ftp.videolan.org/pub/videolan/x264/snapshots/x264-snapshot-20140709-2245-stable.tar.bz2"
MD5SUMLIST="b5a4ab6bc3007e0bbab067dca32def47"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr \
            --enable-shared \
            --disable-cli
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

