#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2014-07-25 / r13664) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2014, The BLFS Development Team

REQUIRES="gtksourceview2 libunique midori mousepad parole ristretto vte2 xfburn xfce4-mixer xfce4-notifyd xfce4-terminal"
TAGS="group"

